### ISSUE TITLE
Features... 

### ISSUE THREAD

**Issue by Snille** [MartinGris/MMM-GoogleMaps-Tracking#1]
Hi! Thank you for this!
I have been thinking of creating a similar module. But now when you already have done it, can I wish for some new features? :)

1. Possibility to track multiple targets (if not "unlimited" at least two), we have two cats. :)
2. Possibility to change the "marker" to a (definable) picture.
3. Possibility to change the map type to "satellite". 

Again, thank you for this! :)

**Comment by MartinGris** [comment]
Hi! Thanks for your ideas!

All 3 should be possible. I will work on it tomorrow ;)

**Comment by Snille** [comment]
Thank you! Great to hear, I forked anyway, just to mock around a bit. :)
Make the "zoom" a variable as well. It's better to give the "user" the choice...  :)

**Comment by MartinGris** [comment]
Hey, check out the new version and take a look in the updated readme. If there are still any questions don't hesitate to ask me for help

**Comment by Snille** [comment]
Nice!! That was fast! :) Now I just have to fix my Node Red node to output the correct json. :)
Please add the "mapTypeId:self.config.mapType" under the "zoom:self.config.zoom". Then you (I) can change to 'satellite' map in the config with "mapType". :)

Just figured out another thing, add a (definable) class to every marker (div), that way you (I) can target it via CSS and make all kinds of cool stuff on the markers. :)

Thank you!

**Comment by MartinGris** [comment]
Hi. mapType can be set now.

I have to check how a class can be attached to each marker-div. the markers are created with google javascript library

**Comment by Snille** [comment]
Great! Thank you! :) I'll close the "issue" now. The class thing is just "nice to have". :)

**Comment by Snille** [comment]
I'm pulling the data from our cat's [GPS necklaces](https://tractive.com/) in to Home Assistant, then HA updates the Mirror every minute. :)
Just for fun... This is how it looks... On my mirror: 
![image](https://user-images.githubusercontent.com/1011699/98703068-678a5280-237b-11eb-9214-f4e926cf94a6.png)
And the actual map...
![image](https://user-images.githubusercontent.com/1011699/98702489-b5528b00-237a-11eb-9f68-88304e401943.png)
Thank you! :)

**Comment by MartinGris** [comment]
Very nice!

Here is what I do with the module. I'm displaying the parkposition of my car:

![mirror](https://user-images.githubusercontent.com/4095936/98706075-b1286c80-237e-11eb-84ec-ff842c905682.jpg)
