### ISSUE TITLE
MarkerWithLabel is not defined

### ISSUE THREAD

**Issue by ruudvddries** [MartinGris/MMM-GoogleMaps-Tracking#13]
After installing MMM-GoogleMaps-Tracking, hooking it up with a API key and congifuring the module in config.js like this;

    {
      module: 'MMM-GoogleMaps-Tracking',
      header: 'Where is everyone?',
      position: 'bottom_right',
      config: {
        apikey: 'google-maps-apikey',
        lat: '52.173582517790564',
        lon: '5.819538980950757',
        zoom: 11,
        mapType: 'roadmap',
        marker: [
          {
            label: 'Test',
            lat: '52.173582517790564',
            lon: '5.819538980950757'
          },
        ]

      }
    },

I get the following error: 
Uncaught ReferenceError: MarkerWithLabel is not defined
    at MMM-GoogleMaps-Tracking.js:152:5
    
What am I doing wrong?

**Comment by MartinGris** [comment]
Hi,
have you installed all the dependencies by:

cd MMM-GoogleMaps-Tracking
npm install

?

**Comment by ruudvddries** [comment]
Yes, I have done git command to get the repo to my docker. Done a npm install from MMM-GoogleMaps-Tracking and haven't seen the need to install other dependencies.

So it should be a fresh install.

**Comment by MartinGris** [comment]
Nevertheless the MarkerWithLabel package seems to be missing. Can you check if it s existing in 'node_modules/@googlemaps/markerwithlabel' ?

**Comment by ruudvddries** [comment]
Almost the latest response ever. I just had a look and I do have a markerwithlabel folder.

**Comment by ruudvddries** [comment]
Reinstalled MMM-GoogleMaps-Tracking via NPM and now it works flawless. 

Thanks for your efforts and patience!
