### ISSUE TITLE
Updating positions...

### ISSUE THREAD

**Issue by Snille** [MartinGris/MMM-GoogleMaps-Tracking#2]
Hi again! :)
I'm trying to get my updating from Home Assistant to work via sending the updates using MMM-Remote-Control.
But first I'm trying to figure out "what" to send.
So, this is my config first:
```javascript
		{
			disabled: false,
			module: 'MMM-GoogleMaps-Tracking',
			position: 'middle_center',
			classes: "None",
			config: {
				apikey: '---- secret ----',
				lat: '57.174193',
				lon: '13.971835',
				zoom: 18,
				mapType: 'satellite',
				marker:[
					{
						lat: '57.174193',
						lon: '13.971835',
						icon: 'https://www.snille.net/img/hass/users/Kakan-In-60x60.png'
					},
					{
						lat: '57.174293',
						lon: '13.971935',
						icon: 'https://www.snille.net/img/hass/users/Cappuccino-In-60x60.png'
					},
				]
			 }
		},
```
Then I'm trying to "curl" the new data just to see that it works.
I'll send the whole JSON array (with both markers) like this:

`$ curl -X POST http://MagicMirrorIP:8080/api/notification/UPDATE_POSITION -H 'content-type: application/json' -d '[{"lat":57.174193,"lon":13.971535,"icon":"https://www.snille.net/img/hass/users/Kakan-In-60x60.png"},{"lat":57.174393,"lon": 13.971235,"icon":"https://www.snille.net/img/hass/users/Cappuccino-In-60x60.png"}]'`

I get this response back: `{"success":true,"notification":"UPDATE_POSITION","payload":{"0":{"lat":57.174193,"lon":13.971535,"icon":"https://www.snille.net/img/hass/users/Kakan-In-60x60.png"},"1":{"lat":57.174393,"lon":13.971235,"icon":"https://www.snille.net/img/hass/users/Cappuccino-In-60x60.png"}}}`

But nothing happens on the mirror. No markers are moved or changed.

So I tried to send just one "marker" update like this: 

`$ curl -X POST http://MagicMirrorIP:8080/api/notification/UPDATE_POSITION -H 'content-type: application/json' -d '{"lat":57.174193,"lon":13.971535,"icon":"https://www.snille.net/img/hass/users/Kakan-In-60x60.png"}'`

I get this response: `{"success":true,"notification":"UPDATE_POSITION","payload":{"lat":57.174193,"lon":13.971535,"icon":"https://www.snille.net/img/hass/users/Kakan-In-60x60.png"}}`

And one marker is "moved" (replaced with the standard marker picture) and the other marker is (of course) removed. The position of the moved marker is correct but the picture is "lost"...

Let me know if you need any more information. :)

**Comment by MartinGris** [comment]
Hi!
You forget to insert the "marker" array property. Your JSON should look like this:
{
    marker:[
	   {
		  "lat":57.174193,
		  "lon":13.971535,
		  "icon":"https://www.snille.net/img/hass/users/Kakan-In-60x60.png"
	   },
	   {
		  "lat":57.174393,
		  "lon":13.971235,
		  "icon":"https://www.snille.net/img/hass/users/Cappuccino-In-60x60.png"
	   }
	]
}

Nice cats by the way :D

**Comment by Snille** [comment]
Oh, haha. Of course! :) It works! Thank you!

And thanks, I'm going to use these pictures instead, looks better... 
https://www.snille.net/img/hass/users/Kakan-Out-64x70-point.png 
https://www.snille.net/img/hass/users/Cappuccino-Out-64x70-point.png
