### ISSUE TITLE
More then one...

### ISSUE THREAD

**Issue by Snille** [MartinGris/MMM-GoogleMaps-Tracking#3]
Hi again, it's me. :)
Just figured out a problem, If you want more then one instance of the module, there is no way to send the notification to a specific module, all modules get's the "notifications".
Also no way to address each module with CSS (or maybe it is with the module number?)... 
I would like to have the module at least 4 times in total, showing different markers depending on the profile selected... :)

**Comment by MartinGris** [comment]
Hi,

check out this documentation of the [Remote Control REST Api](https://documenter.getpostman.com/view/6167403/Rzfni66c).
With 'http://localhost:8080/api/module/:moduleName/:action' you can adress a module instance. I think with 'http://localhost:8080/api/modules' you get the names of the module instances. 

This names should also be usable for css

**Comment by Snille** [comment]
Oh, thank you, I'll have to do some testing. But it looks good. :) I just have to build something in HA to "filter" out the correct module(s) to send to... Should be possible... I think. :)
