### ISSUE TITLE
New request... :)

### ISSUE THREAD

**Issue by Snille** [MartinGris/MMM-GoogleMaps-Tracking#4]
I'm looking for a way to add a "label" on the marker.
Found this: https://github.com/googlemaps/js-markerwithlabel
Can be installed with npm... 
Fiddle here: https://jsfiddle.net/m9xfws6j/72/
Looks like this...
![image](https://user-images.githubusercontent.com/1011699/98952700-0a69da80-24fc-11eb-83a1-91b4e6ef07e0.png)
Then you can add the "time" in the json-object, to get it to update at the same time as the position...
````json
		marker:[
			{        
				time: "13:23",
				lat: "<LATITUDE>",
				lon: "<LONGITUDE>"
				icon: "ICON_URL"
			},
			{        
				time: "12:54",
				lat: "<LATITUDE>",
				lon: "<LONGITUDE>"
				icon: "ICON_URL"
			},
			{        
				time: "11:41",
				lat: "<LATITUDE>",
				lon: "<LONGITUDE>"
				icon: "ICON_URL"
			}
		]
````
Then you will know WHEN you parked your car! :)
What do you think?

**Comment by Snille** [comment]
Maybe it's better to just call the "extra" field for extra or data. It does not have to be a time... :)

**Comment by MartinGris** [comment]
Good idea. I also prefer a general solution for an optional label text. I will work on it on sunday. But feel free to create a pull request.

**Comment by Snille** [comment]
Great! I'm trying to figure things out... I'll PR if I get it... :)

**Comment by Snille** [comment]
Done! PR sent... Looks like this now:
![image](https://user-images.githubusercontent.com/1011699/99145072-c0a00200-266b-11eb-89e4-79835884c42a.png)
Iv'e added the time and the battery status of the GPS tracker to the "label" field. And the picture changes depending on if the "cat-door" has set the cat to in or out. :)

**Comment by MartinGris** [comment]
Nice job! Thanks for the development of the new label feature ;)
