### ISSUE TITLE
Not an issue.... 

### ISSUE THREAD

**Issue by Snille** [MartinGris/MMM-GoogleMaps-Tracking#6]
If you want another picture, as an example how it CAN look...
You can use this one: https://www.snille.net/img/magicmirror/decoration/MapsWithCats.png
![image](https://user-images.githubusercontent.com/1011699/100555817-5c518500-329e-11eb-9b1a-be58c87a7994.png)
Just to show off.... :)
PS: "Ute" means "Out" (status comes from the [SureFlap Pet Door](https://www.surepetcare.com/en-gb/pet-doors/microchip-cat-flap), then it's the last time it's updated the location and the battery left in % in the [tracker](https://tractive.com/sv/pd/gps-tracker-cat). :)

**Comment by MartinGris** [comment]
Thanks! I put it in the credits section of the readme ;)
