### ISSUE TITLE
display shared location

### ISSUE THREAD

**Issue by GattoJohnny** [MartinGris/MMM-GoogleMaps-Tracking#7]
Hi, this module looks awesome, congratulations. 

Is there a way to display Google Shared location information on the map? Locations of those devices that share their coordinates with the google user who has that particular API key?

**Comment by MartinGris** [comment]
Hi, thanks for the compliment.

Unfortunatel this is not possible. There is a feature request in the Google Issue tracker which is not answered by Google: https://issuetracker.google.com/issues/62938530

You have to find a way to get the current location of your device and send it to this module by a notification as described in the readme.

**Comment by GattoJohnny** [comment]
Thank you.
And I wish you all the best for the New Year!
