### ISSUE TITLE
Error in MMM-GoogleMaps-Tracking.js

### ISSUE THREAD

**Issue by MystaraTheGreat** [MartinGris/MMM-GoogleMaps-Tracking#9]
It looks like lines 6 and 7 need to be removed from MMM-GoogleMaps-Tracking.js.
If you don't set lon and lat in the config file, then these default to the values "latitute" and "longitude".  That, however, causes those strings to be set at the centre point on line 91, which in turn causes map.setCenter to throw an exception (NaN not an expected type) on line 184.

**Comment by MartinGris** [comment]
Fixed in the current commit. Thanks for your support
